[project]
name = "rifs"
version = "0.1.0"
description = "About Python Render Interface Frameworks. Less executables, more python."
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

]
requires-python = ">=3.9"
license = { file = "LICENSE" }
dependencies = [
    "pytest",
    "requests",
    "toml",
    "PyYAML",
    "confuse",
    "anytree",
    "requests",
    "bs4",
]
#[tool.setuptools]
## ...
#package-dir = {"" = "src"}

#[tool.setuptools.package-dir]
#mypkg = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["alfred*"] # alternatively: `exclude = ["additional*"]`
namespaces = false

# Poety Setup
[tool.poetry]
description = "About Python Render Interface Frameworks. Less executables, more python."
name = "rifs"
version = "0.1.0"
authors = ["robert-v <robertvigorito@gmail.com>"]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py37, py38, py39, py310

[testenv]
allowlist_externals = poetry,echo
commands =
    pip install -U pip
    pip install . pytest
    pytest -s -rap .
"""
